spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userSystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: West761009
    driver-class-name:  com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:com/mybatis/**/*.xml
  type-aliases-package: com.mybaits.model
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config: 
      table-underline: false
    